"""Add emergency contact fields to users

Revision ID: b84a6554ad56
Revises: 90bc5cf572a3
Create Date: 2025-11-05 17:21:41.791204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84a6554ad56'
down_revision: Union[str, None] = '90bc5cf572a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emergency_contact_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_relationship', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'emergency_contact_relationship')
    op.drop_column('users', 'emergency_contact_phone')
    op.drop_column('users', 'emergency_contact_name')
    # ### end Alembic commands ###
